theme: jekyll-theme-cayman
title: Yun-Chun Chen
email: ycchen@cs.toronto.edu

show_downloads: "true"
github:
  cv_url: https://yunchunchen.github.io/CV/CV.pdf
  github_url: https://github.com/YunChunChen
  google_scholar_url: https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AJsN-F7Bg9WggHd0xK7qIx-wii596FC5nocE0dDqLWgftb97mNlK91nsTp0O2_7esVZGVOTEgL_L_keUEd5TMoNIZflibtloLjp59VRXe7J6mvSoxzPdMzQ&user=TiCSofEAAAAJ
  dblp_url: https://dblp.uni-trier.de/pers/hd/c/Chen:Yun=Chun
  linkedin_url: https://www.linkedin.com/in/yun-chun-chen-615075164/
